# This file stores configurations for your Shopify app.

scopes = "write_products,read_customers,write_customers,read_products,write_products,read_publications,read_product_listings,read_orders,write_orders"